{% set name = "py3nvml" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fbcotter/py3nvml/archive/{{ version }}.tar.gz
  sha256: e373d638b9cf0bf314d42b56e4875cf73123962072880c3b4b16791ab078ae12

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - enum34      # [py < 34]
    - xmltodict

test:
  imports:
    - py3nvml

about:
  home: https://github.com/fbcotter/py3nvml.git
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python 3 Bindings for the NVIDIA Management Library
  doc_url: https://py3nvml.readthedocs.io/en/latest/
  dev_url: https://github.com/fbcotter/py3nvml.git

extra:
  recipe-maintainers:
    - szymon-kuklewicz
